erDiagram
    USER {
        int user_id PK
    }
    ROLE {
        int role_id PK
        str name
        int created_by FK
        int updated_by FK
    }
    PERSON {
        int person_id PK
        str name
        int role_id FK
        int created_by FK
        int updated_by FK
    }
    TEAM {
        int team_id PK
        int parent_team_id FK
        str name
        int manager
        int created_by FK
        int updated_by FK
    }
    SKILL {
        int skill_id PK
        str name
        int created_by FK
        int updated_by FK
    }
    GOAL {
        int goal_id PK
        int skill_id FK
        str name
        int created_by FK
        int updated_by FK
    }
    PERSONGOAL {
        int persongoal_id PK
        int goal_id FK
        int person_id FK
        int exceeds_score
        date due_date
        int created_by FK
        int updated_by FK
    }
    PERSONSKILL {
        int personskill_id PK
        int person_id FK
        int skill_id FK
        int score
        int created_by FK
        int updated_by FK
    }
    PERSONSKILLHISTORY {
        int personskill_id PK
        int person_id FK
        int skill_id FK
        int score
        date date
        int created_by FK
        int updated_by FK
    }
    TEAMGOAL {
        int teamgoal_id PK
        int goal_id FK
        int team_id FK
        int max_team_score_exceeds
        int avg_score
        date due_date
        int created_by FK
        int updated_by FK
    }
    SKILLTOOL {
        int skilltool_id PK
        int tool_id FK
        int skill_id FK
        int created_by FK
        int updated_by FK
    }
    TOOL {
        int tool_id PK
        str name
        int created_by FK
        int updated_by FK
    }
    TEAMPERSON {
        int teamperson_id PK
        int team_id FK
        int person_id FK
        int created_by FK
        int updated_by FK
    }

    PERSON }|..|{ ROLE : "role_id"
    PERSONSKILL }|..|{ PERSON : "person_id"
    PERSONSKILL }|..|{ SKILL : "skill_id"
    PERSONGOAL }|..|{ GOAL : "goal_id"
    PERSONGOAL }|..|{ PERSON : "person_id"
    PERSONSKILLHISTORY }|..|{ PERSON : "person_id"
    PERSONSKILLHISTORY }|..|{ SKILL : "skill_id"
    GOAL }|..|{ SKILL : "skill_id"
    TEAMGOAL }|..|{ TEAM : "team_id"
    TEAMGOAL }|..|{ GOAL : "goal_id"
    SKILLTOOL }|..|{ SKILL : "skill_id"
    SKILLTOOL }|..|{ TOOL : "tool_id"
    TEAM }|..|{ TEAM : "parent_team_id"
    TEAMPERSON }|..|{ TEAM : "team_id"
    TEAMPERSON }|..|{ PERSON : "person_id"
    %% created_by and updated_by FKs to USER
    PERSON }|..|{ USER : "created_by/updated_by"
    ROLE }|..|{ USER : "created_by/updated_by"
    TEAM }|..|{ USER
